import { Component, signal, computed, OnInit } from '@angular/core';                                                                                                                                               
  import { CommonModule } from '@angular/common';
  import { FormsModule } from '@angular/forms';                                                                                                                                                                      
  import { MatTableModule } from '@angular/material/table';                                                                                                                                                          
  import { MatSortModule, Sort } from '@angular/material/sort';                                                                                                                                                      
  import { MatPaginatorModule, PageEvent } from '@angular/material/paginator';                                                                                                                                       
  import { MatCheckboxModule } from '@angular/material/checkbox';                                                                                                                                                    
  import { MatButtonModule } from '@angular/material/button';                                                                                                                                                        
  import { MatFormFieldModule } from '@angular/material/form-field';                                                                                                                                                 
  import { MatInputModule } from '@angular/material/input';                                                                                                                                                          
  import { MatSelectModule } from '@angular/material/select';                                                                                                                                                        
  import { MatMenuModule } from '@angular/material/menu';                                                                                                                                                            
                                                                                                                                                                                                                     
  interface Order {                                                                                                                                                                                                  
    id: string; customer: string; product: string;                                                                                                                                                                   
    category: string; amount: number; status: string; date: string;                                                                                                                                                  
  }                                                                                                                                                                                                                  
                                                                                                                                                                                                                     
  const ORDERS: Order[] = Array.from({ length: 50 }, (_, i) => ({                                                                                                                                                    
    id: `#${4600 - i}`,                                                                                                                                                                                              
    customer: ['Alice Johnson','Bob Smith','Carol White','Dan Brown','Eva Martinez',                                                                                                                                 
               'Frank Lee','Grace Kim','Henry Wilson','Iris Chen','Jake Park'][i % 10],                                                                                                                              
    product:  ['Pro Plan','Starter Plan','Enterprise','Add-on Pack','Consulting'][i % 5],
    category: ['Subscription','One-time','Service','License'][i % 4],                                                                                                                                                
    amount:   Math.round((Math.random() * 500 + 20) * 100) / 100,                                                                                                                                                    
    status:   ['completed','pending','failed','refunded'][i % 4],                                                                                                                                                    
    date:     new Date(2024, 0, (i % 28) + 1).toISOString().split('T')[0],                                                                                                                                           
  }));                                                                                                                                                                                                               
                                                                                                                                                                                                                     
  @Component({                                                                                                                                                                                                       
    selector: 'app-advanced-table',                                                                                                                                                                                  
    standalone: true,                                                                                                                                                                                                
    imports: [CommonModule, FormsModule, MatTableModule, MatSortModule, MatPaginatorModule,                                                                                                                          
              MatCheckboxModule, MatButtonModule, MatFormFieldModule, MatInputModule,
              MatSelectModule, MatMenuModule],template: `                                                                                                                                                                                                      
      <div class="space-y-4 animate-fade-in">                                                                                                                                                                        
        <div>                                                                                                                                                                                                        
          <h1 class="text-2xl font-bold text-primary">Advanced Table</h1>                                                                                                                                            
          <p class="text-muted text-sm mt-1">Full-featured table with filters, selection, and pagination</p>                                                                                                         
        </div>                                                                                                                                                                                                       
                                                                                                                                                                                                                     
        <div class="card">                                                                                                                                                                                           
          <!-- Bulk action bar -->                                                                                                                                                                                   
          @if (selected().size > 0) {                                                                                                                                                                                
            <div class="flex items-center gap-3 mb-4 p-3 bg-accent-50 rounded-lg border border-accent-100 animate-fade-in">                                                                                          
              <span class="text-sm font-medium text-accent-700">{{ selected().size }} selected</span>                                                                                                                
              <button mat-stroked-button class="!text-red-600 !border-red-200 !text-sm" (click)="deleteSelected()">                                                                                                  
                🗑 Delete                                                                                                                                                                                             
              </button>                                                                                                                                                                                              
              <button mat-stroked-button class="!text-sm" (click)="exportSelected()">                                                                                                                                
                ⬇ Export                                                                                                                                                                                             
              </button>                                                                                                                                                                                              
              <button mat-button class="!text-muted !text-sm ml-auto" (click)="clearSelection()">                                                                                                                    
                Clear                                                                                                                                                                                                
              </button>                                                                                                                                                                                              
            </div>                                                                                                                                                                                                   
          }                                                                                                                                                                                                          
                                          
          <!-- Filters -->                                                                                                                                                                                           
          <div class="flex gap-3 mb-4 flex-wrap">                                                                                                                                                                    
            <mat-form-field appearance="outline" class="!w-56">                                                                                                                                                      
              <mat-label>Search orders</mat-label>                                                                                                                                                                   
              <input matInput [(ngModel)]="search" placeholder="Customer, product...">
            </mat-form-field>                                                                                                                                                                                        
            <mat-form-field appearance="outline" class="!w-44">                                                                                                                                                      
              <mat-label>Status</mat-label>                                                                                                                                                                          
              <mat-select [(ngModel)]="filterStatus">                                                                                                                                                                
                <mat-option value="">All statuses</mat-option><mat-option value="completed">Completed</mat-option>                                                                                                                                                 
                <mat-option value="pending">Pending</mat-option>                                                                                                                                                     
                <mat-option value="failed">Failed</mat-option>                                                                                                                                                       
                <mat-option value="refunded">Refunded</mat-option>                                                                                                                                                   
              </mat-select>                                                                                                                                                                                          
            </mat-form-field>                                                                                                                                                                                        
            <mat-form-field appearance="outline" class="!w-44">                                                                                                                                                      
              <mat-label>Category</mat-label>                                                                                                                                                                        
              <mat-select [(ngModel)]="filterCategory">                                                                                                                                                              
                <mat-option value="">All categories</mat-option>                                                                                                                                                     
                <mat-option value="Subscription">Subscription</mat-option>                                                                                                                                           
                <mat-option value="One-time">One-time</mat-option>                                                                                                                                                   
                <mat-option value="Service">Service</mat-option>                                                                                                                                                     
                <mat-option value="License">License</mat-option>                                                                                                                                                     
              </mat-select>                                                                                                                                                                                          
            </mat-form-field>                                                                                                                                                                                        
            <button mat-stroked-button class="self-center !text-sm"                                                                                                                                                  
              (click)="search=''; filterStatus=''; filterCategory=''">                                                                                                                                               
              Reset                                                                                                                                                                                                  
            </button>                                                                                                                                                                                                
          </div>                                                                                                                                                                                                     
                                                                                                                                                                                                                     
          <!-- Table -->                                                                                                                                                                                             
          <div class="overflow-x-auto">                                                                                                                                                                              
            <table mat-table [dataSource]="paginated()" matSort (matSortChange)="onSort($event)"                                                                                                                     
                   class="w-full">                                                                                                                                                                                   
                                                                                                                                                                                                                     
              <!-- Checkbox -->                                                                                                                                                                                      
              <ng-container matColumnDef="select">                                                                                                                                                                   
                <th mat-header-cell *matHeaderCellDef>                                                                                                                                                               
                  <mat-checkbox [checked]="allSelected()" [indeterminate]="someSelected()"                                                                                                                           
                    (change)="toggleAll($event.checked)" color="primary"></mat-checkbox>                                                                                                                             
                </th><td mat-cell *matCellDef="let row">                                                                                                                                                                  
                  <mat-checkbox [checked]="selected().has(row.id)"                                                                                                                                                   
                    (change)="toggleRow(row.id)" color="primary"></mat-checkbox>                                                                                                                                     
                </td>                                                                                                                                                                                                
              </ng-container>                                                                                                                                                                                        
                                                                                                                                                                                                                     
              <ng-container matColumnDef="id">                                                                                                                                                                       
                <th mat-header-cell *matHeaderCellDef mat-sort-header class="!text-muted !text-xs">Order</th>                                                                                                        
                <td mat-cell *matCellDef="let row" class="font-mono !text-accent-600 !text-sm">{{ row.id }}</td>                                                                                                     
              </ng-container>                                                                                                                                                                                        
                                                                                                                                                                                                                     
              <ng-container matColumnDef="customer">                                                                                                                                                                 
                <th mat-header-cell *matHeaderCellDef mat-sort-header class="!text-muted !text-xs">Customer</th>                                                                                                     
                <td mat-cell *matCellDef="let row" class="font-medium !text-sm">{{ row.customer }}</td>                                                                                                              
              </ng-container>                                                                                                                                                                                        
                                                                                                                                                                                                                     
              <ng-container matColumnDef="product">                                                                                                                                                                  
                <th mat-header-cell *matHeaderCellDef mat-sort-header class="!text-muted !text-xs">Product</th>                                                                                                      
                <td mat-cell *matCellDef="let row" class="!text-sm">{{ row.product }}</td>                                                                                                                           
              </ng-container>                                                                                                                                                                                        
                                                                                                                                                                                                                     
              <ng-container matColumnDef="category">                                                                                                                                                                 
                <th mat-header-cell *matHeaderCellDef class="!text-muted !text-xs">Category</th>                                                                                                                     
                <td mat-cell *matCellDef="let row">                                                                                                                                                                  
                  <span class="badge badge-accent">{{ row.category }}</span>                                                                                                                                         
                </td>                                                                                                                                                                                                
              </ng-container>                                                                                                                                                                                        
                                                                                                                                                                                                                     
              <ng-container matColumnDef="amount">                                                                                                                                                                   
                <th mat-header-cell *matHeaderCellDef mat-sort-header class="!text-muted !text-xs">Amount</th>                                                                                                       
                <td mat-cell *matCellDef="let row" class="font-semibold !text-sm">                                                                                                                                   
                  {{ row.amount | currency }}                                                                                                                                                                        
                </td>
                </ng-container>                                                                                                                                                                                        
                                                                                                                                                                                                                     
              <ng-container matColumnDef="status">                                                                                                                                                                   
                <th mat-header-cell *matHeaderCellDef class="!text-muted !text-xs">Status</th>                                                                                                                       
                <td mat-cell *matCellDef="let row">                                                                                                                                                                  
                  <span class="badge"                                                                                                                                                                                
                    [class.badge-success]="row.status==='completed'"                                                                                                                                                 
                    [class.badge-warning]="row.status==='pending'"                                                                                                                                                   
                    [class.badge-danger]="row.status==='failed'"                                                                                                                                                     
                    [class.badge-info]="row.status==='refunded'">                                                                                                                                                    
                    {{ row.status }}                                                                                                                                                                                 
                  </span>                                                                                                                                                                                            
                </td>                                                                                                                                                                                                
              </ng-container>                                                                                                                                                                                        
                                                                                                                                                                                                                     
              <ng-container matColumnDef="date">                                                                                                                                                                     
                <th mat-header-cell *matHeaderCellDef mat-sort-header class="!text-muted !text-xs">Date</th>                                                                                                         
                <td mat-cell *matCellDef="let row" class="!text-muted !text-sm">{{ row.date }}</td>                                                                                                                  
              </ng-container>                                                                                                                                                                                        
                                              
              <ng-container matColumnDef="actions">                                                                                                                                                                  
                <th mat-header-cell *matHeaderCellDef></th>                                                                                                                                                          
                <td mat-cell *matCellDef="let row">                                                                                                                                                                  
                  <button mat-icon-button [matMenuTriggerFor]="rowMenu" (click)="$event.stopPropagation()">                                                                                                          
                    ⋯                                                                                                                                                                                                
                  </button>                                                                                                                                                                                          
                  <mat-menu #rowMenu="matMenu">                                                                                                                                                                      
                    <button mat-menu-item>👁 View</button>                                                                                                                                                            
                    <button mat-menu-item>✏️  Edit</button>                                                                                                                                                           
                    <button mat-menu-item class="!text-red-500">🗑 Delete</button>                                                                                                                                    
                  </mat-menu>                                                                                                                                                                                        
                </td>                                                                                                                                                                                                
              </ng-container>
              <tr mat-header-row *matHeaderRowDef="columns" class="border-b border-border"></tr>                                                                                                                     
              <tr mat-row *matRowDef="let row; columns: columns"                                                                                                                                                     
                  class="border-b border-border/50 hover:bg-elevated transition-colors cursor-pointer"                                                                                                               
                  [class.bg-accent-50]="selected().has(row.id)"                                                                                                                                                      
                  (click)="toggleRow(row.id)"></tr>                                                                                                                                                                  
            </table>                                                                                                                                                                                                 
          </div>                                                                                                                                                                                                     
                                                                                                                                                                                                                     
          <!-- Paginator -->                                                                                                                                                                                         
          <mat-paginator                                                                                                                                                                                             
            [length]="filteredData().length"                                                                                                                                                                         
            [pageSize]="pageSize"                                                                                                                                                                                    
            [pageSizeOptions]="[5, 10, 25, 50]"
            (page)="onPage($event)"                                                                                                                                                                                  
            showFirstLastButtons>                                                                                                                                                                                    
          </mat-paginator>                                                                                                                                                                                           
        </div>                                                                                                                                                                                                       
      </div>                                                                                                                                                                                                         
    `,                                                                                                                                                                                                               
  })                                                                                                                                                                                                                 
  export default class AdvancedTableComponent {                                                                                                                                                                      
    columns = ['select','id','customer','product','category','amount','status','date','actions'];                                                                                                                    
                                                                                                                                                                                                                     
    search         = '';                                                                                                                                                                                             
    filterStatus   = '';                                                                                                                                                                                             
    filterCategory = '';                                                                                                                                                                                             
    pageSize       = 10;                                                                                                                                                                                             
    pageIndex      = signal(0);                                                                                                                                                                                      
    sortState      = signal<Sort>({ active: '', direction: '' });                                                                                                                                                    
    selected       = signal<Set<string>>(new Set());                                                                                                                                                                 
                                                                                                                                                                                                                     
    filteredData = computed(() => {                                                                                                                                                                                  
      const term = this.search.toLowerCase();
      return ORDERS.filter(o =>                                                                                                                                                                                      
        (!term || o.customer.toLowerCase().includes(term) || o.product.toLowerCase().includes(term)) &&                                                                                                              
        (!this.filterStatus   || o.status   === this.filterStatus) &&                                                                                                                                                
        (!this.filterCategory || o.category === this.filterCategory)                                                                                                                                                 
      ).sort((a, b) => {                                                                                                                                                                                             
        const { active, direction } = this.sortState();                                                                                                                                                              
        if (!active || !direction) return 0;                                                                                                                                                                         
        const v1 = (a as any)[active], v2 = (b as any)[active];                                                                                                                                                      
        return (v1 < v2 ? -1 : v1 > v2 ? 1 : 0) * (direction === 'asc' ? 1 : -1);                                                                                                                                    
      });                                                                                                                                                                                                            
    });                                                                                                                                                                                                              
                                                                                                                                                                                                                     
    paginated = computed(() => {                                                                                                                                                                                     
      const start = this.pageIndex() * this.pageSize;                                                                                                                                                                
      return this.filteredData().slice(start, start + this.pageSize);                                                                                                                                                
    });                                                                                                                                                                                                              
                                                                                                                                                                                                                     
    allSelected  = computed(() => this.paginated().length > 0 && this.paginated().every(r => this.selected().has(r.id)));                                                                                            
    someSelected = computed(() => this.paginated().some(r => this.selected().has(r.id)) && !this.allSelected());                                                                                                     
                                                                                                                                                                                                                     
    onSort(s: Sort)    { this.sortState.set(s); this.pageIndex.set(0); }                                                                                                                                             
    onPage(e: PageEvent) { this.pageSize = e.pageSize; this.pageIndex.set(e.pageIndex); }
                                                                                                                                                                                                                     
    toggleRow(id: string) {                                                                                                                                                                                          
      this.selected.update(s => { const n = new Set(s); n.has(id) ? n.delete(id) : n.add(id); return n; });                                                                                                          
    }                                                                                                                                                                                                                
                                                                                                                                                                                                                     
    toggleAll(checked: boolean) {                                                                                                                                                                                    
      this.selected.update(s => {                                                                                                                                                                                    
        const n = new Set(s);                                                                                                                                                                                        
        this.paginated().forEach(r => checked ? n.add(r.id) : n.delete(r.id));                                                                                                                                       
        return n;                                                                                                                                                                                                    
      });                                                                                                                                                                                                            
    }
    clearSelection()  { this.selected.set(new Set()); }                                                                                                                                                              
    deleteSelected()  { alert(`Delete ${this.selected().size} orders`); this.clearSelection(); }                                                                                                                     
    exportSelected()  { alert(`Export ${this.selected().size} orders`); }
  }