import { Component } from '@angular/core';                                                                                                                                                                         
                                            
  @Component({                                                                                                                                                                                                       
    selector: 'app-advanced-table',                                                                                                                                                                                  
    standalone: true,                                                                                                                                                                                                
    template: `                                                                                                                                                                                                      
      <div class="animate-fade-in">                                                                                                                                                                                  
        <h1 class="text-2xl font-bold text-primary mb-1">Advanced Table</h1>                                                                                                                                         
        <p class="text-muted text-sm">Advanced table coming soon.</p>                                                                                                                                                
      </div>                                                                                                                                                                                                         
    `,                                                                                                                                                                                                               
  })                                                                                                                                                                                                                 
  export default class AdvancedTableComponent {}