import { Component, inject } from '@angular/core';                                                                                                                                                                 
  import { RouterLink } from '@angular/router';
  import { CommonModule } from '@angular/common';                                                                                                                                                                    
  import { MatMenuModule } from '@angular/material/menu';
  import { MatButtonModule } from '@angular/material/button';                                                                                                                                                        
  import { MatDividerModule } from '@angular/material/divider';                                                                                                                                                      
  import { UiStore } from '../../store/ui.store';                                                                                                                                                                    
  import { ThemeService } from '../../core/services/theme.service';                                                                                                                                                  
  import { AuthService } from '../../core/services/auth.service';                                                                                                                                                    
                                                                                                                                                                                                                     
  @Component({                                                                                                                                                                                                       
    selector: 'app-header',                                                                                                                                                                                          
    standalone: true,                                                                                                                                                                                                
    imports: [CommonModule, RouterLink, MatMenuModule, MatButtonModule, MatDividerModule],                                                                                                                           
    template: `                                                                                                                                                                                                      
      <header class="app-header">                                                                                                                                                                                    
        <div class="flex items-center gap-3">                                                                                                                                                                        
          <button class="icon-btn" (click)="uiStore.toggleSidebar()" title="Toggle sidebar">                                                                                                                         
            ☰                                                                                                                                                                                                       
          </button>                                                                                                                                                                                                  
          <div class="hidden sm:flex items-center gap-1 text-sm text-muted">                                                                                                                                         
            <span>NexusPanel</span>                                                                                                                                                                                  
            <span>/</span>                                                                                                                                                                                           
            <span class="text-primary font-medium">Dashboard</span>                                                                                                                                                  
          </div>                                                                                                                                                                                                     
        </div>                                                                                                                                                                                                       
                                                                                                                                                                                                                     
        <div class="flex items-center gap-2">                                                                                                                                                                        
          <button class="icon-btn" (click)="theme.toggleMode()">                                                                                                                                                     
            {{ theme.mode() === 'dark' ? '☀️ ' : '🌙' }}                                                                                                                                                              
          </button>                                                                                                                                                                                                  
                                                                                                                                                                                                                     
          <button class="icon-btn relative" [matMenuTriggerFor]="notifMenu">                                                                                                                                         
            🔔                                                                                                                                                                                                       
            <span class="absolute -top-0.5 -right-0.5 w-4 h-4 bg-red-500 text-white                                                                                                                                  
                         rounded-full text-xs flex items-center justify-center leading-none">3</span>                                                                                                                
          </button>                                                                                                                                                                                                  
          <mat-menu #notifMenu="matMenu" xPosition="before">                                                                                                                                                         
            <div class="px-4 py-2 border-b border-border">                                                                                                                                                           
              <div class="font-semibold text-sm">Notifications</div>                                                                                                                                                 
            </div>                                                                                                                                                                                                   
            <div class="w-72">                                                                                                                                                                                       
              @for (n of notifications; track n.id) {                                                                                                                                                                
                <button mat-menu-item class="!py-3">                                                                                                                                                                 
                  <div class="flex gap-3 items-start w-full">                                                                                                                                                        
                    <div class="w-2 h-2 rounded-full mt-1.5 flex-shrink-0"                                                                                                                                           
                      [class.bg-accent-500]="!n.read" [class.bg-muted]="n.read"></div>                                                                                                                               
                    <div>                                                                                                                                                                                            
                      <div class="text-sm font-medium">{{ n.title }}</div>                                                                                                                                           
                      <div class="text-xs text-muted">{{ n.time }}</div>                                                                                                                                             
                    </div>                                                                                                                                                                                           
                  </div>                                                                                                                                                                                             
                </button>                                                                                                                                                                                            
              }                                                                                                                                                                                                      
            </div>                                                                                                                                                                                                   
          </mat-menu>                                                                                                                                                                                                
                                                                                                                                                                                                                     
          <button [matMenuTriggerFor]="userMenu" class="flex items-center gap-2 px-2 py-1
                  rounded-lg hover:bg-elevated transition-colors cursor-pointer border-none bg-transparent">                                                                                                         
            <img [src]="auth.currentUser()?.avatar" class="w-8 h-8 rounded-full object-cover"                                                                                                                        
                 alt="avatar" onerror="this.src='https://api.dicebear.com/7.x/initials/svg?seed=U'">                                                                                                                 
            <span class="hidden sm:block text-sm font-medium">{{ auth.currentUser()?.name }}</span>                                                                                                                  
            <span class="text-muted text-xs">▾</span>                                                                                                                                                                
          </button>                                                                                                                                                                                                  
          <mat-menu #userMenu="matMenu" xPosition="before">                                                                                                                                                          
            <button mat-menu-item [routerLink]="['/profile']">👤 Profile</button>                                                                                                                                    
            <button mat-menu-item [routerLink]="['/settings']">⚙️  Settings</button>                                                                                                                                  
            <mat-divider />
            <button mat-menu-item (click)="auth.logout()">🚪 Logout</button>                                                                                                                                         
          </mat-menu>                                                                                                                                                                                                
        </div>                                                                                                                                                                                                       
      </header>                                                                                                                                                                                                      
    `,                                                                                                                                                                                                               
    styles: [`                                                                                                                                                                                                       
      .app-header {                                                                                                                                                                                                  
        display: flex;                                                                                                                                                                                               
        align-items: center;                  
        justify-content: space-between;                                                                                                                                                                              
        height: var(--header-height);                                                                                                                                                                                
        padding: 0 1.5rem;                                                                                                                                                                                           
        background: var(--bg-surface);                                                                                                                                                                               
        border-bottom: 1px solid var(--border-default);                                                                                                                                                              
        position: sticky;                                                                                                                                                                                            
        top: 0;                                                                                                                                                                                                      
        z-index: 50;                                                                                                                                                                                                 
      }                                                                                                                                                                                                              
      .icon-btn {                                                                                                                                                                                                    
        width: 36px; height: 36px;                                                                                                                                                                                   
        border: none; background: none; cursor: pointer;                                                                                                                                                             
        border-radius: var(--radius-md);                                                                                                                                                                             
        display: flex; align-items: center; justify-content: center;                                                                                                                                                 
        font-size: 1rem; color: var(--text-secondary);                                                                                                                                                               
        transition: all 150ms ease; position: relative;                                                                                                                                                              
        &:hover { background: var(--bg-elevated); color: var(--text-primary); }                                                                                                                                      
      }                                                                                                                                                                                                              
    `],                                                                                                                                                                                                              
  })                                                                                                                                                                                                                 
  export class HeaderComponent {                                                                                                                                                                                     
    uiStore = inject(UiStore);                                                                                                                                                                                       
    theme   = inject(ThemeService);                                                                                                                                                                                  
    auth    = inject(AuthService);
    notifications = [                                                                                                                                                                                                
      { id: 1, title: 'New user registered',  time: '2 min ago',   read: false },                                                                                                                                    
      { id: 2, title: 'Monthly report ready', time: '1 hour ago',  read: false },                                                                                                                                    
      { id: 3, title: 'Server usage at 85%',  time: '3 hours ago', read: false },                                                                                                                                    
    ];                                                                                                                                                                                                               
  }