import { Component } from '@angular/core';                                                                                                                                                                         
                                            
  @Component({                                                                                                                                                                                                       
    selector: 'app-form-validation',                                                                                                                                                                                 
    standalone: true,                                                                                                                                                                                                
    template: `                                                                                                                                                                                                      
      <div class="animate-fade-in">                                                                                                                                                                                  
        <h1 class="text-2xl font-bold text-primary mb-1">Form Validation</h1>                                                                                                                                        
        <p class="text-muted text-sm">Form validation coming soon.</p>                                                                                                                                               
      </div>                                                                                                                                                                                                         
    `,                                                                                                                                                                                                               
  })                                                                                                                                                                                                                 
  export default class FormValidationComponent {}