import { Component } from '@angular/core';                                                                                                                                                                         
                                                                                                                                                                                                                     
  @Component({                                                                                                                                                                                                       
    selector: 'app-modals',                                                                                                                                                                                          
    standalone: true,      
    template: `                                                                                                                                                                                                      
      <div class="animate-fade-in">                                                                                                                                                                                  
        <h1 class="text-2xl font-bold text-primary mb-1">Modals</h1>                                                                                                                                                 
        <p class="text-muted text-sm">Modals coming soon.</p>                                                                                                                                                        
      </div>                                                                                                                                                                                                         
    `,                                                                                                                                                                                                               
  })                                                                                                                                                                                                                 
  export default class ModalsComponent {}