import { ApplicationConfig, provideZoneChangeDetection } from '@angular/core';                                                                                                                                     
  import { provideRouter, withComponentInputBinding, withViewTransitions, withPreloading, PreloadAllModules } from '@angular/router';                                                                                
  import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';                                                                                                                               
  import { provideHttpClient } from '@angular/common/http';                                                                                                                                                          
  import { provideCharts, withDefaultRegisterables } from 'ng2-charts';                                                                                                                                              
  import { routes } from './app.routes';                                                                                                                                                                             
                                                                                                                                                                                                                     
  export const appConfig: ApplicationConfig = {                                                                                                                                                                      
    providers: [                                                                                                                                                                                                     
      provideZoneChangeDetection({ eventCoalescing: true }),                                                                                                                                                         
      provideRouter(                                                                                                                                                                                                 
        routes,                                                                                                                                                                                                      
        withComponentInputBinding(),                                                                                                                                                                                 
        withViewTransitions(),                                                                                                                                                                                       
        withPreloading(PreloadAllModules),                                                                                                                                                                           
      ),                                                                                                                                                                                                             
      provideAnimationsAsync(),                                                                                                                                                                                      
      provideHttpClient(),                                                                                                                                                                                           
      provideCharts(withDefaultRegisterables()),                                                                                                                                                                     
    ],                                                                                                                                                                                                               
  };